FROM java:openjdk-8u45-jdk
MAINTAINER chris@chrisrichardson.net
EXPOSE 8080
CMD java -jar spring-boot-user-registration-webapp-1.0-SNAPSHOT.jar
ADD build/spring-boot-user-registration-webapp-1.0-SNAPSHOT.jar .

